### ISSUE TITLE
Production: figure 5-1 cut off

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkPython2#2]
Fig 5-1 the letters get cut off on the left
- From what I can tell, that's a problem in the source image file. We'd need to redraw it, unless he has a good copy.

**Comment by kristenORM** [comment]
I will ask our illustrator to redraw this, unless you have a copy that is not cut off (the problem is in the image file itself)

**Comment by AllenDowney** [comment]
Let me see if I can fix it.

**Comment by AllenDowney** [comment]
I just pushed a new version of figs/stack2.pdf, as well as two other figures that needed correction.

But when I rebuild the PDF, I don't see the changes.  Are you pulling the figures from different files?

**Comment by kristenORM** [comment]
Yes, when the book went through intake, the images were renamed with numbers instead of descriptive names, and are in the /images directory. Using numbers instead of names helps us ensure that nothing is missing.

If you want to email me the updated figures directly, I will pass those along to our illustrator, who is processing them all to make sure the resolution and size meet printer standards. If you're able to tell me which figures they are (5-1 instead of stack2.pdf), that would be helpful as well.

**Comment by AllenDowney** [comment]
They are

Figure 5-1 which is stack2.pdf
Figure 7-1 which is assign2.pdf
Figure 10-1 which is liststate.pdf

**Comment by kristenORM** [comment]
Got it, thanks!
